# Assignment Numpy Basic



Consider the below code to answer further questions:
import numpy as np
list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]
array_list = np.array(object = list_)


### Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.
**Ans :-**

In [7]:
import numpy as np
list_ = [ '1' , '2' , '3', '4' ,'5']
array_list = np.array(object = list_)
print("Data type of list_ :- ",type(list_))
print("Data type of array_list :- ",type(array_list))

Data type of list_ :-  <class 'list'>
Data type of array_list :-  <class 'numpy.ndarray'>


### Q2. Write a code to print the data type of each and every element of both the variables list_ and array_list.
**Ans :-**

In [9]:
for item in list_:
    print("Data type of element of list_ :- ",type(item))
for item in array_list:
    print("Data type of element of array_list :- ",type(item))

Data type of element of list_ :-  <class 'str'>
Data type of element of list_ :-  <class 'str'>
Data type of element of list_ :-  <class 'str'>
Data type of element of list_ :-  <class 'str'>
Data type of element of list_ :-  <class 'str'>
Data type of element of array_list :-  <class 'numpy.str_'>
Data type of element of array_list :-  <class 'numpy.str_'>
Data type of element of array_list :-  <class 'numpy.str_'>
Data type of element of array_list :-  <class 'numpy.str_'>
Data type of element of array_list :-  <class 'numpy.str_'>


### Q3. Considering the following changes in the variable, array_list:
array_list = np.array(object = list_, dtype = int)
### Will there be any difference in the data type of the elements present in both the variables, list_ and array_list? If so then print the data types of each and every element present in both the variables, list_ and array_list.
**Ans:-**

In [11]:
array_list = np.array(object = list_, dtype = int)

for item in list_:
    print("Data type of element of list_ :- ",type(item))
for item in array_list:
    print("Data type of element of array_list :- ",type(item))

Data type of element of list_ :-  <class 'str'>
Data type of element of list_ :-  <class 'str'>
Data type of element of list_ :-  <class 'str'>
Data type of element of list_ :-  <class 'str'>
Data type of element of list_ :-  <class 'str'>
Data type of element of array_list :-  <class 'numpy.int64'>
Data type of element of array_list :-  <class 'numpy.int64'>
Data type of element of array_list :-  <class 'numpy.int64'>
Data type of element of array_list :-  <class 'numpy.int64'>
Data type of element of array_list :-  <class 'numpy.int64'>


Consider the below code to answer further questions:

import numpy as np

num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]

num_array = np.array(object = num_list)
### Q4. Write a code to find the following characteristics of variable, num_array:
### (i) shape
### (ii) size

In [12]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [14]:
num_array.shape

(2, 3)

In [15]:
num_array.size

6

### Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.
**Ans:-**

In [16]:
zero_array = np.zeros((3, 3))
print("Array of zeros:")
print(zero_array)

Array of zeros:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


### Q6. Create an identity matrix of shape (5,5) using numpy functions?
**Ans :-**

In [17]:
identity_matrix = np.identity(5)
print("Identity matrix:")
print(identity_matrix)

Identity matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
